"""empty message

Revision ID: f6e5e0afc2a2
Revises: d655c84d3823
Create Date: 2023-12-12 04:11:04.180236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e5e0afc2a2'
down_revision = 'd655c84d3823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_record_number', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('medical_record_number')

    # ### end Alembic commands ###
